### ISSUE TITLE
.mid to .sng converter occasionally produces bad output

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2024-Swadge-FW#155]
These midis produce identical .sng files (only 1 included) that are much shorter than all other .sng files. They don't play in firmware or the emulator, and seem to act like 0-note songs.
[jukebox.zip](https://github.com/AEFeinstein/Swadge-IDF-5.0/files/13445073/jukebox.zip)

type 0 vs type 1 midi:
type 1 is the good kind for this purpose
type 0 always outputs as one track, type 1 preserves track info, but type 0 is the only one supported by some daws natively (e.g. Ableton Live)

**Comment by AEFeinstein** [comment]
When I've run into MIDIs that don't convert right, I've loaded them up in https://signal.vercel.app/?lang=en or https://www.audacityteam.org/ and re-saved them. That's helped.

**Comment by Brycey92** [comment]
Just updated the issue description with an excerpt from a DM between FuryfulFawful and I.

**Comment by AEFeinstein** [comment]
FWIW I used https://github.com/Gegel85/midi_parser to parse the MIDIs.. There's zero documentation.

**Comment by AEFeinstein** [comment]
Will keep this in mind when expanding on MIDI processing this year.

**Comment by AEFeinstein** [comment]
Closing b/c it looks like we're going to use MIDI as-is this year.
