### ISSUE TITLE
Mac OS documentaion improvements

### ISSUE THREAD

**Issue by johnnywycliffe** [AEFeinstein/Super-2024-Swadge-FW#204]
**Description**
Mac OS documentation has a few errors that came up as I was working on getting my working environment up and running. 

**Current shortfalls**
- Documentation does not explicitly indicate that some of the step for linux just above need to be reproduced (Primarily downloading the esp-idf from git)
- CMake is not included on the list of programs required
- the command to stop the pulseaudio service is 'brew services **stop** pulseaudio" not "start"
- MacOS will build the project just fine as long as it's run through xQuartz with source export.sh run.
- COM ports are /dev/tty* on Linux and /dev/cu.* on MacOS. Added in some clarification.

**Affected Version**
 - Platform: MacOS
 - git branch: main
 - git hash: 0cbf9f3

**Comment by AEFeinstein** [comment]
#206 was merged. You don't need to reopen the ticket for each documentation update. If you put "#204" in the commit message, it'll get referenced here automatically.
