### ISSUE TITLE
Swadge Zine

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-FW#217]
**Summary**
Wouldn't it be neat to have a little comic zine on each Swadge, just like Tea Room has?

**Comment by dylwhich** [comment]
Sounds like a good use case for resurrecting the markdown renderer! And I think the markdown parsing could actually be moved to be part of asset processing instead of doing it at runtime, so we'd just load up a static markdown tree and the accompanying text blob

**Comment by AEFeinstein** [comment]
Oh, I figured this would be more of an image sideshow

**Comment by dylwhich** [comment]
Ahh, I totally missed the "comic" part, woops. One of these days I'll find a problem that can be solved with markdown!!

**Comment by AEFeinstein** [comment]
There was some chatter about a dating sim or text adventure or something, which would be ripe for MD!

**Comment by AEFeinstein** [comment]
Artist wrangling is hard, so I'm gonna shelve this for now.
