### ISSUE TITLE
Soko Puzzle Game Mode

### ISSUE THREAD

**Issue by hunterdyar** [AEFeinstein/Super-2024-Swadge-FW#218]
Working on Sokoban, again.

Greg on sprite art, @BlueScrewy also on programming (again).

Tasks: [https://github.com/users/hunterdyar/projects/9/](https://github.com/users/hunterdyar/projects/9/)

**Comment by AEFeinstein** [comment]
@hunterdyar not sure why this got closed. It ain't done. Get to it!

**Comment by AEFeinstein** [comment]
Merged! I want to write some instructions on the main menu though
