### ISSUE TITLE
Issue with drawWsgSimpleScaled()

### ISSUE THREAD

**Issue by DebrisHauler** [AEFeinstein/Super-2024-Swadge-FW#228]
**Description**
Issue with drawWsgSimpleScaled()

**Expected behavior**
Rendering a sprite with slightly negative y should render a cropped portion onto the screen similar to rendering a sprite with a slightly negative x. It seems the issue is only in the y direction.

**Reproduction Steps**
Scale up a sprite rendered to a slightly negative y position. The sprite is pushed down to start at y=0 instead of being clipped.

**Screenshots**
See sprites in the big bug video that are going off the left side of the screen clip correctly. But sprites going off the top of the screen are pushed down. Issue is only with scaled sprites.
(https://github.com/AEFeinstein/Super-2024-Swadge-FW/issues/221#issuecomment-2119533918)

**Logs**
n/a

**Affected Version**
 - Platform: Windows
 - git branch: main
 - git commit: b36f6fe
 - git full sha: b36f6fe8b5cd21ad33f164a8498ce63d4fe0fc41

**Additional Notes**
n/a

**Comment by dylwhich** [comment]
Interesting. It looks like when this happens it does actually clip the sprite, but it does it at the bottom instead.

**Comment by AEFeinstein** [comment]
There ended up being another issue here which I resolved in 7f160072febdaaff1edd98b21afdf132e6416ec2
