### ISSUE TITLE
Pango

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-FW#232]
To be filled out by @JVeg199X 

----

**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_

**Technical Spec**
_How will this be implemented?_
_What peripherals will be used, and how?_

**UI**
_What are the display screens & menus (if applicable)?_
_What user inputs are there for each screen?_

**Mockups**
_Paste any mockups of screens or anything else here._

**How to Test**
How can we verify the feature is working?

**Comment by emilyanthony4244** [comment]
I noticed in the Pango tutorial the player is instructed to hit Start. This should be changed to match the button labels on the Swadge.
