### ISSUE TITLE
Pretty Keyboard

### ISSUE THREAD

**Issue by johnnywycliffe** [AEFeinstein/Super-2024-Swadge-FW#240]
**Summary**
The current keyboard is white text on a black background. It should be prettier.

**Technical Spec**
A simple added background with some boxes to keep the text visible on screen. Colors can be set for the shadowboxes and text. Drop in replacement for the old keyboard to not break compatibility.  

**Usage**
Instead of calling `textEntryStart()` call `textEntryStartPretty()` with the following arguments:
- Font pointer
- Max length of the string
- Character buffer pointer
- Background image pointer
- Shadowbox color
- Text color

Otherwise, use textEntryDraw() and textEntryInput() as before.

**How to test**
In the PrettyKeeb branch:
Run ./swadge_emulator.exe -m Keyboard Test

Edit background, text color, and shadowbox color in main/modes/test/keebTest/keebTest.c

**Example**
![Screenshot 2024-06-28 150209](https://github.com/AEFeinstein/Super-2024-Swadge-FW/assets/26311939/241be4bc-b228-4b3e-9b05-55d7caf8f43f)

**Comment by AEFeinstein** [comment]
Snazzy! This keyboard was originally written for an SSD1306 monochrome display, so I'm glad it's getting a fresh coat of paint!

One thing to note is that the cursor blink is way off. `textEntryDraw()` should take `elapsedUs` as an argument and run an accurate timer like:
```c
bool cursorIsShowing = false;
...

// Flip cursorIsShowing every quarter second (250000 uS)
cursorTimer += elapsedUs;
while(cursorTimer >= 250000)
{
    cursorTimer -= 250000;
    cursorIsShowing = !cursorIsShowing;
}

if(cursorIsShowing)
{
    drawLineFast(...);
}
```

**Comment by johnnywycliffe** [comment]
I haven't touched the blinking yet lol. I noticed that the end function for the keyboard literally does nothing despite having a comment "Disarms the cursor blink" so I figure that was broken a while ago.

I can look into it,

**Comment by AEFeinstein** [comment]
Yeah... I bet it was used in one mode and worked there, so that was that. I'm all for incidentally making it suck less!

**Comment by johnnywycliffe** [comment]
Added a few new features:
- Refactored to get rid of a lot of old references (Covered by "swadge2024.h")
- Emphasis color options
- A way to change the text color, background, emphasis color, and shadowbox color after initial start call
- Added blinking, see note below
- Added a new "return" style enter key
- Reformatted code to match more modern styles

Note:
Blinking might be a bit sporadic, I think it's my test program, but `TextEntryInput()` seems to be blocking.

**Comment by AEFeinstein** [comment]
@johnnywycliffe is there more stuff you wanted to do here, or is it closeable?

**Comment by johnnywycliffe** [comment]
Close it.
