### ISSUE TITLE
Game - 2048

### ISSUE THREAD

**Issue by johnnywycliffe** [AEFeinstein/Super-2024-Swadge-FW#244]
**Summary**
The most addictive game of... 2014. Let's call this the anniversary edition.

**Technical Spec**
Needs a rock to run on. It's... not hard. Requires only basic functions of the swadge.

**UI**
Uses A or B to accept some results, uses directional controls to move blocks. Start resets the game.

No assets are requires aside from two fonts. An updated splash screen might need more?

**Screenshots**
Title:
![image](https://github.com/AEFeinstein/Super-2024-Swadge-FW/assets/26311939/62cb746e-fe3c-4fd8-8761-524ab2404159)

Gameplay:
![image](https://github.com/AEFeinstein/Super-2024-Swadge-FW/assets/26311939/0a158ca9-4e9f-4c5b-a28a-611837acb5d6)

Player reaches 2048:
![image](https://github.com/AEFeinstein/Super-2024-Swadge-FW/assets/26311939/65e549d2-3116-4bab-971b-f70734eaa392)

Game Over:
![image](https://github.com/AEFeinstein/Super-2024-Swadge-FW/assets/26311939/31c4d738-9a45-416b-b47f-27dfc01db278)

**Features planned for 1.1**
- LEDs that color based on highes score block and pulse during a merge
- Sounds
- Better splash screen
- High score saving
- Fix colors of blocks to be easily discerned (Green blocks are too similar)

**Comment by AEFeinstein** [comment]
Woo! For the blocks, have you considered using sprites instead of flat colors? That way you could get textures or something cute idk.

**Comment by AEFeinstein** [comment]
Also this would be hilarious to play with tilt controls

**Comment by johnnywycliffe** [comment]
Movement controls should be easy enough to roll into 1.1.

I'm worried about identification of blocks if I make them too busy with sprites. It might be a good idea to use circles for the higher level ones just so they're visually distinct and then I can reuse colors, but since I already have a problem with recognition, I don't think making a pattern is a good idea.

**Comment by AEFeinstein** [comment]
Up to you, though I'll note that for the color-challenged, like myself, differentiating something like stripes v. polka dots is much easier

**Comment by johnnywycliffe** [comment]
Wasn't thinking about that. Let me see what I can do.

**Comment by AEFeinstein** [comment]
You can also do cool things like use a different, bigger font, and have some blending around font edges. I wouldn't worry too much about the set of tiles. Art can always be filled in later, and with community help if that's your jam :)

**Comment by johnnywycliffe** [comment]
I'm very much not an art person. I'll take all the help I can get in the art department.

**Comment by johnnywycliffe** [comment]
Version 1.1:
- New, easier to read sprites for the tiles
- Sounds for button clicks and BGM
- A new splash screen with visual interest and high score displayed
- High score saved between resets
- LEDs on the side now illuminate to help show player which direction the blocks moved, or if they didn't move
- LEDs also provide more visual interest in non-gameplay modes
