### ISSUE TITLE
Ultimate TTT: Empty squares are sometimes impossible to navigate to

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2024-Swadge-FW#267]
**Description**
If the bottom-right square in a subgame is empty, but the rest of the bottom row and right column are filled, the cursor cannot be moved from the top-left section to the bottom-right square.

**Expected behavior**
You should somehow be able to move down and to the right simultaneously. This seems to be possible already for the top left and right corners 

**Reproduction Steps**
_Steps to reproduce the behavior and how often it occurs._
1. Fill up the rightmost  column and the bottom row with markers, except for the bottom-right corner.
2. Try to select the corner

**Screenshots**
See this image for an example of the situation, outlined in white - the square with the white circle cannot be accessed:
![cant-move](https://github.com/user-attachments/assets/7c9c2aa7-5b8f-4b64-85ec-cfcb7170a9ad)

**Comment by AEFeinstein** [comment]
I could have sworn I accounted for that. It's an odd path, but if you click down it should move down one row, try that whole row, then wrap, try that row, and finally try the middle row. Transpose it for right.
![image](https://github.com/user-attachments/assets/b7e42dca-da03-4c9b-8a3d-d05ad54c640a)

**Comment by AEFeinstein** [comment]
Maybe `tttHandleGameInput()` is overly complicated and also broken :(

**Comment by dylwhich** [comment]
Getting back to this in a timely fashion, I tried moving down in that situation and that just wraps it to the top of that column instead. This issue doesn't happen in all rotations of the shape though so it might depend on whether horizontal or vertical wrapping happens first or something?

**Comment by AEFeinstein** [comment]
@dylwhich I'll leave this to you to fix, unless you kick it back to me. Hot potato ticket!
