### ISSUE TITLE
Palette Swapping for WSGs

### ISSUE THREAD

**Issue by johnnywycliffe** [AEFeinstein/Super-2024-Swadge-FW#290]
**Summary**
A feature currently missing is the ability to create a palette a la the NES/SNES and have the sprite's colors swapped out automatically. This feature is one that would likely be useful to many programmers down the road for a variety of applications as it allows for smaller sized games with more variety

**Technical Spec**
A new file in the main/display folder, wsgPalette.h. It provides the following new functions:
- drawWSGPalette(); Automatically draws a wsg with the pallet given
- wsgPaletteReset(): Sets the palette back to default
- wsgPaletteSet(): Sets an individual color
- wsgPaletteSetGroup(): Sets a group of colors to swap

Additionally, the wsg.h and .c files need to be updated to avoid code duplication and to fix a few dependency issues.

**How to Test**
Go to any mode drawing wsgs

```C
// In modeData_t
{
    wsgPalette_t pal;
}

// In modeEnter
{
    // Palette setup
    wsgPaletteReset(&pal);
    wsgPaletteSet(&pal, c000, c555);
}

// Where the WSG is drawn
{
    drawWsgPalette(&wsg, x, y, &pal, vertFilp, HorFlip, rotation);
}

**Comment by AEFeinstein** [comment]
Conceptually this is good. If anyone starts to run into performance issues, it may be worth considering recoloring the source WSG once, rather than swapping palette on each draw. That would increase RAM usage if the same WSG gets recolored twice in the same frame because you'd need it twice in RAM instead. Food for thought.

**Comment by johnnywycliffe** [comment]
I was going to do that, but in the end a simple map adds a single cycle per pixel. Not nothing, but not much.

It really depends on if we end up speed limited before we end up RAM limited, and for now it seems we have overhead in both.
