### ISSUE TITLE
Improve MIDI Playback Performance

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2024-Swadge-FW#299]
**Summary**
The MIDI engine hasn't been optimized yet and we're running low on cycles so we should take a look

**Technical Spec**
List of random things to look into later, vaguely in order of how much I think they'll help with no real basis:

 * Move ADSR logic into sw synth, because it kind of already does this a bit anyway and will probably simplify the logic
 * Check for events less frequently, as the MIDI tick rate is vastly slower than the sample rate
 * Clean up the logic that decides whether to check for the next event. It's pretty complicated and it might be faster to just always do the check once
 * Look for 64-bit cars and math
 * Less interpolation with slightly more state
 * Check if all those `__builtin_ctz` and `__builtin_popcount` calls are actually turning into single instructions
 * Only sum oscillators for voices that are actually active (but this might allow "heavier" parts of songs to slow stuff down vs. always doing the same amount of work regardless)

**Comment by AEFeinstein** [comment]
I'd also recommend using https://github.com/KDAB/hotspot to profile the emulator and see where the cycles are going. It's not the same as the firmware, but it should be close enough to find any big offenders. I used it when optimizing texture lookups for the raycaster last year.

The makefile target for generating code coverage data can also be kinda helpful for profiling a specific function be looking at the number of times each line is run

**Comment by AEFeinstein** [comment]
Some idea of spots to look at
![image](https://github.com/user-attachments/assets/518f52fe-265e-4e31-a47a-a761ce446a0d)

**Comment by AEFeinstein** [comment]
Good as we're getting!
