### ISSUE TITLE
cGrove Grove background doesn't draw on hardware

### ISSUE THREAD

**Issue by johnnywycliffe** [AEFeinstein/Super-2024-Swadge-FW#320]
**Description**
When using actual Swadge hardware, the grove Background doesn't load, leaving ghosting all around the screen.

**Expected behavior**
The background WSG is drawn to the screen each frame

**Reproduction Steps**
Load Chowa Grove on swadge hardware, then select "play with Chowa". Finish the tutorial, and when you press start the screen will not change to be the grove.

**Affected Version**
 - Platform: Firmware
 - git branch: cGrove
 - git hash: [89f1fbf](https://github.com/AEFeinstein/Super-2024-Swadge-FW/commit/89f1fbfcf30ebe22ddaaab486a6bc4e5d47ceef9)

**Comment by AEFeinstein** [comment]
Yep, this is a size limit. Using some [nifty functions](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32s2/api-reference/system/heap_debug.html#heap-information) we can see how much space there is, both free and the largest block:
```c
#include <esp_heap_caps.h>
#include <esp_log.h>

...

ESP_LOGI("CG", "free size %zu, largest block %zu\n",
    heap_caps_get_free_size(MALLOC_CAP_SPIRAM),
    heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM));
```
I put that right before `garden_background.wsg` gets loaded and saw:
```
I (277588) CG: free size 358644, largest block 249856
```
Thats about ~360kb free with the largest block at ~250kb. An 800x600 image is 480kb, so you're blowing through both of those limits.

Some quick math says the largest image to draw would be 566 x 424. Or draw a plain green background and draw grass/stump/tree/water sprites on top.

**Comment by johnnywycliffe** [comment]
Made the sprite smaller. Blargh.
