### ISSUE TITLE
No Midi sounds in any modes after entering and exiting light dance mode.

### ISSUE THREAD

**Issue by DebrisHauler** [AEFeinstein/Super-2024-Swadge-FW#322]
**Description**
No Midi sounds in any modes after entering and exiting light dance mode.

**Expected behavior**
Enter light dance mode, then enter any other game mode and hear the music.

**Reproduction Steps**
Enter light dance mode, then enter any other game mode that should have music.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Logs**
_If applicable, add logs from when the problem occurred._

**Affected Version**
 - Platform: Windows, Linux
 - git branch: `main`
 - git hash: 3e1dea07ffd722fbaf9066add2cbcd982a902aff

**Additional Notes**
_Add any other notes about the problem_

**Comment by AEFeinstein** [comment]
Fixed in the `bigbug` branch
