### ISSUE TITLE
Big Bug: Character Dialogue Bug on hardware

### ISSUE THREAD

**Issue by DebrisHauler** [AEFeinstein/Super-2024-Swadge-FW#325]
**Description**
A specific character line starting with "Ooey gooey" brings up about 6 of Garbotnik's portraits. This does not happen in the emulator. The camera also jumps around unexpectedly for this particular dialogue on hardware.

**Expected behavior**
The camera should arrive at the tutorial egg. Then one garbotnik portrait should appear. As seen in the emulator.

**Reproduction Steps**
Flash to hardware. Press a until you see the description happen.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Logs**
_If applicable, add logs from when the problem occurred._

**Affected Version**
 - Platform: Firmware
 - git branch: bigbug
 - git hash: 82999399fd3b92c6bc0a3f2f36aa9952bb2f836f

**Additional Notes**
_Add any other notes about the problem_

**Comment by AEFeinstein** [comment]
I was wondering why this ticket disappeared!
